FROM python:3.8
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
COPY ./eclinic_api/requirements.txt /app/
RUN pip install -r requirements.txt
COPY . /app/
RUN python ./eclinic_api/manage.py migrate
RUN python ./eclinic_api/manage.py createsuperuser
RUN python ./eclinic_api/manage.py runserver
EXPOSE 8000
CMD ["python","manage.py","runserver","0.0.0.0:8000"]